---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI

# Подкачка — в сжатой памяти (zram), отдельный раздел не нужен
userSwapChoices:
    - none
    - file
initialSwapChoice: none

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
showNotEncryptedBootMessage: false

# Btrfs: мгновенные снимки системы и откат обновлений через Timeshift
defaultFileSystemType: "btrfs"
availableFileSystemTypes: ["btrfs", "ext4", "xfs"]

enableLuksAutomatedPartitioning: true
luksGeneration: luks2

partitionLayout:
    - name: "duoos_boot"
      filesystem: ext4
      noEncrypt: true
      onlyPresentWithEncryption: true
      mountPoint: "/boot"
      size: 2G
    - name: "DuoOS"
      filesystem: unknown
      mountPoint: "/"
      size: 100%
