---
doAutologin: false
setRootPassword: false
doReusePassword: true
sudoersGroup: sudo
defaultGroups:
    - adm
    - cdrom
    - dip
    - lpadmin
    - plugdev
    - sudo
    - name: docker
      must_exist: false
      system: true
    - name: sambashare
      must_exist: false
      system: true
# Простые требования к паролю: пользователь сам решает, насколько сложный пароль нужен
passwordRequirements:
    minLength: 4
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: true
user:
    shell: /usr/bin/zsh
    forbidden_names: [ root, nobody, daemon, bin, sys, sync, games, man, lp, mail, news, uucp, proxy,
                       www-data, backup, list, irc, apt, sddm, polkitd, rtkit, colord, geoclue, syslog,
                       messagebus, avahi, cups-pk-helper, dnsmasq, tss, uuidd, docker ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "${first}-aisktagos"
    forbidden_names: [ localhost ]
