# Установщик DuoOS (Calamares).
# Шаги мастера: Язык → Регион → Клавиатура → Диск → Пользователь → Проверка → Установка → Готово
---
modules-search: [ local ]

instances:
- id: efi_grub
  module: contextualprocess
  config: contextualprocess_efi_grub.conf
- id: duoos_post
  module: shellprocess
  config: shellprocess_duoos_post.conf
- id: logs
  module: shellprocess
  config: shellprocess_logs.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - initramfscfg
  - initramfs
  - grubcfg
  - contextualprocess@efi_grub
  - bootloader
  - packages
  - shellprocess@duoos_post
  - shellprocess@logs
  - umount
- show:
  - finished

branding: duoos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
