# Терминал DuoOS (kitty, отрисовка на GPU)
font_family      JetBrains Mono
font_size        11.0
disable_ligatures never
cursor_shape     beam
cursor_blink_interval 0.6
scrollback_lines 20000
enable_audio_bell no
window_padding_width 8
hide_window_decorations no
confirm_os_window_close 1
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
background_opacity 0.94
background_blur 1
shell zsh
copy_on_select clipboard

# Цвета
foreground #e4e5f1
background #11131f
selection_background #3b3570
cursor #8b7dff
color0  #1b1e2e
color8  #4b5068
color1  #ff5f57
color9  #ff7b74
color2  #28c840
color10 #5be37a
color3  #febc2e
color11 #ffd166
color4  #6d8bff
color12 #93a8ff
color5  #b18cff
color13 #c9adff
color6  #22d3ee
color14 #67e8f9
color7  #c9cce6
color15 #ffffff
active_tab_background #6d5dfc
active_tab_foreground #ffffff
inactive_tab_background #1b1e2e
inactive_tab_foreground #9aa0bd

# Сочетания как в macOS/VS Code
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
